"""add serving fields to food_items

Revision ID: 3c89d85c9aa2
Revises: 5b38fccfe089
Create Date: 2026-03-21 23:42:37.464916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c89d85c9aa2'
down_revision: Union[str, Sequence[str], None] = '5b38fccfe089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_items', sa.Column('unit_size_g', sa.Float(), nullable=True))
    op.add_column('food_items', sa.Column('serving_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_items', 'serving_label')
    op.drop_column('food_items', 'unit_size_g')
    # ### end Alembic commands ###
