"""add goal fields to user_profiles

Revision ID: 5b38fccfe089
Revises: 3446d52a869e
Create Date: 2026-03-21 23:17:42.035912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b38fccfe089'
down_revision: Union[str, Sequence[str], None] = '3446d52a869e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('calorie_goal', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('protein_goal', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('carbs_goal', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('fat_goal', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'fat_goal')
    op.drop_column('user_profiles', 'carbs_goal')
    op.drop_column('user_profiles', 'protein_goal')
    op.drop_column('user_profiles', 'calorie_goal')
    # ### end Alembic commands ###
